# ....................................Genztechs...........................................
# ...................................Assignment 4.......................................
# ...............................Data Science Internship.........................
# ....................................Hamza Aslam.......................................

### 1. Arithmetic Mean

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import trim_mean, mode
from sklearn.linear_model import LinearRegression 
import seaborn as sns
import statistics

In [40]:
data = sns.load_dataset("tips")
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [41]:
# Read the CSV file
# data = pd.read_csv('/content/numbers.csv') 
# Calculate Arithmetic Mean 
arithmetic_mean = data['total_bill'].mean() 
print("Arithmetic Mean:") 
print(arithmetic_mean)

Arithmetic Mean:
19.78594262295082


### 2. Weighted Mean

In [42]:
data = np.array([[1, 2, 3],
                 [5, 6, 7],
                 [9, 10, 11]])
weights = [0.3, 0.4, 0.3] # Example weights for each column 
weighted_mean = np.average(data, weights=weights, axis=1) 
print("Weighted Mean:")
print(weighted_mean)

Weighted Mean:
[ 2.  6. 10.]


### 3. Trimmed Mean

In [43]:
trimmed_mean = trim_mean(data, proportiontocut=0.1)
trimmed_mean

array([5., 6., 7.])

### 4. Median

In [44]:
# Calculate Median 
x = [2, 5, 8, 11, 14, 18, 21, 22, 25, 30]
median = np.median(x) 
print("Median:") 
print(median)

Median:
16.0


### 5. Mode

In [45]:
# Read the CSV file
# data = pd.read_csv('/content/numbers.csv') # Replace with the actual file path 
# Calculate Mode
mode_values = statistics.mode(x)
print("Mode:")
print(mode_values)

Mode:
2


### 6. Standard Deviation

In [46]:
std_dev = np.std(x) 
print("Standard Deviation:") 
print(std_dev)

Standard Deviation:
8.662563131083086


### 7. Regression and Correlation

In [47]:
# Dummy Data
data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5],  # Independent variable
    'y': [2, 4, 6, 8, 10]  # Dependent variable
})
x = data.iloc[:, 0] # Assuming the first column is the independent variable
y = data.iloc[:, 1] # Assuming the second column is the dependent variable
regression_model = LinearRegression() 
regression_model.fit(x.values.reshape(-1, 1), y) 
slope = regression_model.coef_[0]
intercept = regression_model.intercept_ 
print("Regression Line: y =", slope, "* x +", intercept) 
correlation_coefficient = data.corr().iloc[0, 1] 
print("Correlation Coefficient:") 
print(correlation_coefficient)


Regression Line: y = 2.0000000000000004 * x + -1.7763568394002505e-15
Correlation Coefficient:
1.0


### 8. Box Plot

In [48]:
# Load the CSV file
df = sns.load_dataset("tips")
# Create a box plot
sns.boxplot(data=df,x="sex",y="total_bill",hue="sex")
plt.title('Box Plot') 
plt.show()

### 9. Euclidean distance

In [49]:
import numpy as np
from scipy.spatial.distance import euclidean
def calculate_euclidean_distance(vector1, vector2): 
    return euclidean(vector1, vector2)
# Example usage
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
# Calculate Euclidean distance
euclidean_distance = calculate_euclidean_distance(vector_a, vector_b)
# Print the result
print("Euclidean Distance:", euclidean_distance)
# Euclidean Distance: 5.196152422706632

Euclidean Distance: 5.196152422706632


### 10.Z Score

In [51]:
from scipy.stats import zscore
# Read the CSV file
data = pd.read_csv('z_scores.csv') 
# Calculate z-scores
z_scores = data.apply(zscore) 
print("Z-Scores:")
print(z_scores)

Z-Scores:
   Column 1  Column 2  Column 3
0 -1.414214 -1.414214 -1.414214
1 -0.707107 -0.707107 -0.707107
2  0.000000  0.000000  0.000000
3  0.707107  0.707107  0.707107
4  1.414214  1.414214  1.414214


### 11.Manhatan Distance

In [52]:
from scipy.spatial.distance import pdist,squareform
# Read the CSV file
data = pd.read_csv('z_scores.csv') 
# Calculate Manhattan distance matrix
manhattan_dist = pdist(data, metric='cityblock') 
manhattan_dist_matrix = squareform(manhattan_dist) 
# Print the distance matrix
print("Manhattan Distance Matrix:") 
print(manhattan_dist_matrix) 

Manhattan Distance Matrix:
[[0.         2.12132034 4.24264069 6.36396103 8.48528137]
 [2.12132034 0.         2.12132034 4.24264069 6.36396103]
 [4.24264069 2.12132034 0.         2.12132034 4.24264069]
 [6.36396103 4.24264069 2.12132034 0.         2.12132034]
 [8.48528137 6.36396103 4.24264069 2.12132034 0.        ]]


### 12.Minkowski distance

In [3]:
from scipy.spatial.distance import cdist 
from scipy.spatial.distance import cdist 
# Read the CSV file
data = pd.read_csv('z_scores.csv') 
# Calculate Minkowski distance matrix
p = 2 # Choose the desired order of Minkowski distance (p=1 for Manhattan distance, p=2 for Euclidean distance)
minkowski_dist = cdist(data, data, metric='minkowski', p=p) 
# Print the distance matrix
print("Minkowski Distance Matrix:") 
print(minkowski_dist)

Minkowski Distance Matrix:
[[0.         1.22474487 2.44948974 3.67423461 4.89897949]
 [1.22474487 0.         1.22474487 2.44948974 3.67423461]
 [2.44948974 1.22474487 0.         1.22474487 2.44948974]
 [3.67423461 2.44948974 1.22474487 0.         1.22474487]
 [4.89897949 3.67423461 2.44948974 1.22474487 0.        ]]


### 13.Supremum Distance

In [4]:
from scipy.spatial.distance import cdist
# Read the CSV file
data = pd.read_csv('z_scores.csv')
# Calculate Supremum distance matrix
supremum_dist = cdist(data, data, metric='chebyshev')
# Print the distance matrix 
print("Supremum Distance Matrix:") 
print(supremum_dist)


Supremum Distance Matrix:
[[0.         0.70710678 1.41421356 2.12132034 2.82842712]
 [0.70710678 0.         0.70710678 1.41421356 2.12132034]
 [1.41421356 0.70710678 0.         0.70710678 1.41421356]
 [2.12132034 1.41421356 0.70710678 0.         0.70710678]
 [2.82842712 2.12132034 1.41421356 0.70710678 0.        ]]


### 14.Chi-Square

In [5]:
from scipy.stats import chi2_contingency
# Read the CSV file
data = pd.read_csv('chi2_contingency_table.csv', index_col=0)

data = data.astype(int)  # Convert to integers if needed
# Perform Chi-Square test 
chi2_results = chi2_contingency(data) 
chi2_statistic = chi2_results[0] 
p_value = chi2_results[1]
print("Chi-Square Test:")
print("Chi-Square Statistic:", chi2_statistic) 
print("P-value:", p_value)


Chi-Square Test:
Chi-Square Statistic: 30.0
P-value: 4.894437128029217e-06


### 15.covariance matrix

In [7]:
# Read the CSV file
data = pd.read_csv('numbers.csv')
# Calculate covariance matrix 
cov_matrix = data.cov()
# Print the covariance matrix 
print("Covariance Matrix:") 
print(cov_matrix)

Covariance Matrix:
     X    Y    Z
X  2.5 -2.5  2.5
Y -2.5  2.5 -2.5
Z  2.5 -2.5  2.5


### 16.hamming_distance

In [9]:
def hamming_distance(x, y): 
    return np.sum(x != y)/ len(x)
# Example usage 
x = "abcde"
y = "axcye"
hamming_dist = hamming_distance(list(x), list(y)) 
print("Hamming Distance:", hamming_dist)


Hamming Distance: 0.2


### 17.jaccard_distance

In [10]:
def jaccard_distance(x, y):
    intersection = len(set(x).intersection(set(y))) 
    union = len(set(x).union(set(y)))
    return 1 - intersection / union
# Example usage 
x = [1, 2, 3, 4, 5]
y = [4, 5, 6, 7, 8]
jaccard_dist = jaccard_distance(x, y) 
print("Jaccard Distance:", jaccard_dist)

Jaccard Distance: 0.75


### 18.gower_distance

In [20]:
import pandas as pd
from scipy.spatial import distance

# Define Gower's distance function
def gower_distance(x, y):
    num_dist = distance.euclidean([x['Age']], [y['Age']])
    bin_dist = distance.hamming([x['Gender']], [y['Gender']])
    ord_dist = distance.cityblock([x['Income']], [y['Income']])
    return num_dist, bin_dist, ord_dist

# Load the CSV file
data = pd.read_csv('gower_distance_data.csv')

# Sample data points
x = {'Age': data['Age'][0], 'Gender': data['Gender'][0], 'Income': data['Income'][0]}
y = {'Age': data['Age'][1], 'Gender': data['Gender'][1], 'Income': data['Income'][1]}

# Set weights
weights = {'Age': 0.5, 'Gender': 0.3, 'Income': 0.2}

# Calculate Gower's distance
num_dist, bin_dist, ord_dist = gower_distance(x, y)

# Print the results
print("Numeric Dissimilarity:", num_dist)
print("Binary Dissimilarity:", bin_dist)
print("Ordinal Dissimilarity:", ord_dist)


Numeric Dissimilarity: 5.0
Binary Dissimilarity: 1.0
Ordinal Dissimilarity: 10000


### 19.spearmanr

In [21]:
from scipy.stats import spearmanr
# Example usage 
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]
spearman_dist, _ = spearmanr(x, y) 
spearman_distance = 2 * (1 - spearman_dist) 
print("Spearman's Distance:",spearman_distance)

Spearman's Distance: 4.0
